"""create_documents_and_knowledge_tables

Revision ID: 2ff49b90f2c8
Revises: f31981969248
Create Date: 2026-09-16 14:13:25.943859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff49b90f2c8'
down_revision: Union[str, Sequence[str], None] = 'f31981969248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', name='documenttype', native_enum=False), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('book_series', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_subject'), ['subject'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('lesson', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_lesson'), ['lesson'], unique=False)

    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('SUBJECT', 'GRADE', 'BOOK', 'CHAPTER', 'LESSON', 'TOPIC', 'CONCEPT', 'LEARNING_OBJECTIVE', name='knowledgenodetype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_node_type'), ['node_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_node_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_document_id'))

    op.drop_table('knowledge_nodes')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_lesson'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_chapter'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_subject'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_grade'))

    op.drop_table('documents')
    # ### end Alembic commands ###
